// GENERATED by scripts/derivePmLayout.mjs — do not edit by hand.
// Source: ABP Price List January 2026 Update v (version 1).xlsx
// Regenerate whenever ASUS ships a new price list, then re-check the paste alignment.
import type { ProductLineCode } from '@/types/specForm';

/**
 * How an ASUS PM datasheet is laid out, and in what order its rows appear.
 *
 * The app's upload template mirrors this order so that "convert the PM file" is one copy and
 * one paste instead of ~75 individual cell copies per model. Two consumers: `specTemplate`
 * orders the generated template by it, and `pmDatasheetImport` uses it only to warn when an
 * uploaded sheet has drifted from what was recorded.
 *
 * These are *labels*, not field keys, so this is not a second copy of the catalog — keys are
 * resolved through the same `buildFieldLookup` everything else uses. A label here that
 * resolves to no field still gets a template row, which is how a not-yet-catalogued ASUS row
 * stays paste-aligned instead of shifting everything below it.
 */

/** A sheet qualifies as a datasheet when A2 is "Part No" and A9 is "Sales Model Name". */
export const PM_PART_NO_ROW = 2;
export const PM_MODEL_NAME_ROW = 9;
export const PM_FIRST_MODEL_COL = 2;

export interface PmSheetSpec {
  sheetName: string;
  line: ProductLineCode;
  /** TKDN sheets carry separate, non-overlapping models and are grouped apart in the picker. */
  group: 'main' | 'tkdn';
}

/** The sheets seen in the reference workbook. Detection is structural, so this is a hint. */
export const PM_DATASHEETS: PmSheetSpec[] = [
  { sheetName: 'Commercial Notebook Datasheet', line: 'NX', group: 'main' }, // 34 models
  { sheetName: 'Desktop Datasheet', line: 'PF', group: 'main' }, // 52 models
  { sheetName: 'All-in-One Datasheet', line: 'PT', group: 'main' }, // 50 models
  { sheetName: 'TKDN_Notebook Datasheet', line: 'NX', group: 'tkdn' }, // 25 models
  { sheetName: 'TKDN_AiO_Datasheet', line: 'PT', group: 'tkdn' }, // 18 models
  { sheetName: 'TKDN_DT Datasheet', line: 'PF', group: 'tkdn' }, // 11 models
];

/**
 * Column-A labels in PM print order. `null` marks a blank PM row, mirrored in the template as
 * a reserved spacer — PM rows 3-8 hold the embedded product images, which is why Part No is
 * row 2 and Sales Model Name is row 9.
 *
 * Chromebook has no PM datasheet; it falls back to the catalog's own category order.
 */
export const PM_ROW_ORDER: Record<ProductLineCode, (string | null)[]> = {
  // Commercial Notebook Datasheet — 76 labelled rows
  NX: [
    'Part No',
    null,
    null,
    null,
    null,
    null,
    null,
    'Sales Model Name',
    'EAN Code',
    'UPC Code',
    'WEEE',
    'BASE UNIT',
    'Operating System',
    'Office',
    'LCD cover-material',
    'LCD cover-color',
    'Top case-material',
    'Top case-color',
    'Bottom case-material',
    'Bottom case-color',
    'Military grade',
    'Panel Size',
    'Backlit',
    'OLED',
    'Brightness',
    'Resolution',
    'Glare',
    'Color gamut',
    'View angle(H/V)',
    'Response time(Typ/Max) (ms)',
    'Refresh rate',
    'Contrast  (Typ)',
    'Touch Panel',
    'Screen-to-body ratio',
    'Pantone',
    'IPS-level',
    'VESA CERTIFIED Display HDR',
    'Processor',
    'Neural processor',
    'Chipset',
    'Discrete/Share',
    'Integrated GPU',
    'VRAM',
    'How to upgrade memory',
    'Expansion Slot(includes used)',
    'On board memory',
    'DIMM Memory',
    'Total System Memory',
    'Storage',
    'Front-facing camera',
    'Wireless',
    'On board Wireless',
    'NumberPad',
    'FingerPrint',
    'Keyboard type',
    'I/O ports',
    'Audio',
    'Battery',
    'AC Adapter',
    'Required charging power',
    'Dimension (WxHxD)',
    'Weight (with Battery)',
    'Weight (w/o Battery)',
    'Security',
    'Antivirus',
    'MyASUS feature',
    'Built-in Apps',
    'Disclaimer for Built-in Apps',
    'Included in the Box',
    'Reparability Index (for France)',
    'Reparability Index (for Belgium)',
    'Ecolabels & Compliances',
    'Base Warranty',
    'Recommended Warranty Package Part number//Extension and/or upgrade service from base warranty',
    'Battery warranty',
    'Sustainable Material_Top cover(A part)',
    'Sustainable Material_Keyboard frame (C part)',
    'Sustainable Material_Bottom cover (D part)',
    'Sustainable Material_Battery',
    'Sustainable Material_Keyboard',
    'Sustainable Material_Speaker',
    'Sustainable Material_Total PCR recycled plastic',
  ],
  CB: [],
  // All-in-One Datasheet — 59 labelled rows
  PT: [
    'Part No',
    null,
    null,
    null,
    null,
    null,
    null,
    'Sales Model Name',
    'EAN Code',
    'UPC Code',
    'WEEE',
    'BASE UNIT',
    'ID Color',
    'Panel Size',
    'Resolution',
    'Panel Tech',
    'Brightness',
    'NTSC %',
    'View angle(H/V)',
    'Response time(Typ/Max) (ms)',
    'Refresh rate',
    'Contrast (Typ)',
    'Screen-to-body ratio',
    'IPS-level',
    'Glare',
    'Touch Panel',
    'Stand type',
    'On board processor',
    'Chipset',
    'VRAM',
    'Integrated GPU',
    'DIMM Memory',
    'Total System Memory',
    'Storage',
    'Expansion Slot(includes used)',
    'Easy Upgrade',
    'Optical Drive',
    'Wireless',
    'LAN',
    'Front-facing camera',
    'Privacy Shutter',
    'Harman/Kardon',
    'Audio',
    'Operating System',
    'Office',
    'Voice control',
    'AC Adapter',
    'Side I/O Port',
    'Back I/O Port',
    'Dimension (WxHxD)',
    'Weight',
    'Weight_2',
    'Security',
    'Antivirus',
    'Trusted Platform Module',
    'Built-in Apps',
    'My ASUS features',
    'Included in the box',
    'Ecolabels & Compliances',
    'Base Warranty',
    'Recommended Warranty Package Part number//Extension and/or upgrade service from base warran',
    'Sustainable Material_Front frame',
    'Sustainable Material_Rear cover',
    'Sustainable Material_Base cover',
    'Sustainable Material_Total PCR recycled plastic',
  ],
  // Desktop Datasheet — 47 labelled rows
  PF: [
    'Part No',
    null,
    null,
    null,
    null,
    null,
    null,
    'Sales Model Name',
    'EAN Code',
    'UPC Code',
    'WEEE',
    'BASE UNIT',
    'Size',
    'Color',
    'Form Factor',
    'Operating System',
    'Office',
    'Processor',
    'CPU Cooler',
    'Chipset',
    'DIMM Memory',
    'Memory Speed',
    'Memory Max.',
    'Graphics',
    'Integrated GPU',
    'Storage',
    'Optical Drive',
    'LAN',
    'Audio',
    'Wireless',
    'Power Supply',
    'Rear I/O Port',
    'Front I/O Port',
    'Drive Bay',
    'Serial ATA',
    'Expansion Slot(includes used)',
    'Keyboard & Mouse',
    'Accessory',
    'Dimension (WxDxH)',
    'Weight',
    'My ASUS features',
    'MyExpert Features',
    'Built-in Apps',
    'Adobe Creative Cloud Hard Bundle',
    'Security',
    'Antivirus',
    'TPM',
    'Ecolabels & Compliances',
    'Base Warranty',
    'Recommended Warranty Package Part number//Extension and/or upgrade service from base warran',
    'Sustainable Material_Front bezel',
    'Sustainable Material_I/O bezel',
    'Sustainable Material_Total PCR recycled plastic',
  ],
};
